appname: thichtienganh-quiz-be

port: "5555"
secretkeysentry:
projectsentry:

sql:
  name: db-postgres
  host: 150.230.222.54
  port: 5432
  username: "tuan"
  password: "GPEwCeXQqQGwmtLd"
  database: "postgres"

redis:
  name:
  host:
  port:
  password:
  redisdb:
  keyprefix:

jwt:
  secretkey:
  secretexpireminutes: